name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all platforms
        run: task build
        env:
          VERSION: ${{ github.ref_name }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
